name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install requests
    - name: Run Scripts
      run: |
        mkdir SSTAP_Rules/rules
        python scripts/Discord.py
        python scripts/CHNRoute.py
    - name: Release
      uses: Ricky-Hao/action-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        ASSET_PATH: SSTAP_Rules/rules
        TAG_NAME: latest
        NAME: latest
        
