name: SSTAP Rules Builder

on: 
  push:
    branches:
    - master
  schedule:
  - cron: 0 0 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install requests
    - name: Run Scripts
      run: |
        mkdir rules
        python scripts/Discord.py
        python scripts/CHNRoute.py
        echo "##[set-env name=BODY;]$(date +%Y%m%d)"

    - name: Release
      uses: Ricky-Hao/action-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ASSET_PATH: rules
        TAG_NAME: Latest
        NAME: Latest
        
